//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.sfdsfdsf12
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Dog.
    /// </summary>
    //  *** Start programmer edit section *** (Dog CustomAttributes)

    //  *** End programmer edit section *** (Dog CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("DogE", new string[] {
            "Age as \'Age\'",
            "DogName as \'Dog name\'",
            "Weight as \'Weight\'"})]
    [View("DogL", new string[] {
            "Age as \'Age\'",
            "DogName as \'Dog name\'",
            "Weight as \'Weight\'"})]
    public class Dog : IIS.sfdsfdsf12.Animal
    {
        
        private int fAge;
        
        private string fDogName;
        
        //  *** Start programmer edit section *** (Dog CustomMembers)

        //  *** End programmer edit section *** (Dog CustomMembers)

        
        /// <summary>
        /// Age.
        /// </summary>
        //  *** Start programmer edit section *** (Dog.Age CustomAttributes)

        //  *** End programmer edit section *** (Dog.Age CustomAttributes)
        public virtual int Age
        {
            get
            {
                //  *** Start programmer edit section *** (Dog.Age Get start)

                //  *** End programmer edit section *** (Dog.Age Get start)
                int result = this.fAge;
                //  *** Start programmer edit section *** (Dog.Age Get end)

                //  *** End programmer edit section *** (Dog.Age Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Dog.Age Set start)

                //  *** End programmer edit section *** (Dog.Age Set start)
                this.fAge = value;
                //  *** Start programmer edit section *** (Dog.Age Set end)

                //  *** End programmer edit section *** (Dog.Age Set end)
            }
        }
        
        /// <summary>
        /// DogName.
        /// </summary>
        //  *** Start programmer edit section *** (Dog.DogName CustomAttributes)

        //  *** End programmer edit section *** (Dog.DogName CustomAttributes)
        [StrLen(255)]
        public virtual string DogName
        {
            get
            {
                //  *** Start programmer edit section *** (Dog.DogName Get start)

                //  *** End programmer edit section *** (Dog.DogName Get start)
                string result = this.fDogName;
                //  *** Start programmer edit section *** (Dog.DogName Get end)

                //  *** End programmer edit section *** (Dog.DogName Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Dog.DogName Set start)

                //  *** End programmer edit section *** (Dog.DogName Set start)
                this.fDogName = value;
                //  *** Start programmer edit section *** (Dog.DogName Set end)

                //  *** End programmer edit section *** (Dog.DogName Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "DogE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DogE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DogE", typeof(IIS.sfdsfdsf12.Dog));
                }
            }
            
            /// <summary>
            /// "DogL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View DogL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("DogL", typeof(IIS.sfdsfdsf12.Dog));
                }
            }
        }
    }
}
